import { AppProvider } from '@/store/provider';
import { Header } from './components/header/header';
import './globals.scss';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
